apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tank
  name: tank-order
  labels:
    app: tank-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tank-order
  template:
    metadata:
      labels:
        app: tank-order
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
        resources:
            {{- toYaml .Values.resources | nindent 12 }}

